import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {


  const locale = useLocale();

  if (params.locale !== locale) {
    return notFound();
  }
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
